// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD7_OazWx2UTKMirjvKt9-xfOQKNHvHGg',
    appId: '1:721018866056:web:9b8f2d61f388fcdaf6523d',
    messagingSenderId: '721018866056',
    projectId: 'elsa-cabquiz',
    authDomain: 'elsa-cabquiz.firebaseapp.com',
    storageBucket: 'elsa-cabquiz.firebasestorage.app',
    measurementId: 'G-MMW8FR7Z18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbgdc5-gAiVMt_NGNf6SaFmHSspwnIf1c',
    appId: '1:721018866056:android:537e6d897602ce00f6523d',
    messagingSenderId: '721018866056',
    projectId: 'elsa-cabquiz',
    storageBucket: 'elsa-cabquiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsYzlnehnnnZp3EZuKYJMlWL_kF7CJZ50',
    appId: '1:721018866056:ios:5bd5b70484cdb432f6523d',
    messagingSenderId: '721018866056',
    projectId: 'elsa-cabquiz',
    storageBucket: 'elsa-cabquiz.firebasestorage.app',
    iosBundleId: 'com.example.cabquiz',
  );

}